name: Deploy Sealos Website

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    permissions:
        actions: read # Only required for private GitHub Repo
        contents: read
        deployments: write
        pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull environment variables
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build
        run: vercel build --prod --local-config ./vercel.json
      - name: Link to Vercel
        run: vercel link -t ${{ secrets.VERCEL_TOKEN }} -p ${{ secrets.VERCEL_PROJECT_ID }} --scope ${{ secrets.VERCEL_ORG_ID }} -y
      - name: Deploy to Vercel
        run: vercel deploy --prod --local-config ./vercel.json --archive=tgz --prebuilt --token=${{ secrets.VERCEL_TOKEN }}